services:
  mongodb:
    image: mongo:7
    container_name: aiip-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: inventory_intelligence
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  # backend:
  #   build: ./apps/backend
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     MONGODB_URI: mongodb://mongodb:27017/inventory_intelligence
  #   depends_on:
  #     mongodb:
  #       condition: service_healthy

volumes:
  mongodb_data:
