export const WAREHOUSE_ALLOCATION_STATUS = {
  ALLOCATED: "ALLOCATED",
  OUT_OF_STOCK: "OUT_OF_STOCK",
} as const;

export const WAREHOUSE_DISTANCE_FALLBACK_KM = {
  ASSIGNED_WAREHOUSE: 0,
  SAME_PINCODE: 2,
  SAME_CITY: 10,
  SAME_STATE: 50,
  DIFFERENT_STATE: 250,
} as const;
