export const NOTIFICATION_EVENT_TYPES = {
  RECOMMENDATION_APPROVED: "RECOMMENDATION_APPROVED",
  WAREHOUSE_ALLOCATED: "WAREHOUSE_ALLOCATED",
  PURCHASE_ORDER_CREATED: "PURCHASE_ORDER_CREATED",
  WORKFLOW_COMPLETED: "WORKFLOW_COMPLETED",
  WORKFLOW_FAILED: "WORKFLOW_FAILED",
  SALES_OPTIMIZATION_APPROVED: "SALES_OPTIMIZATION_APPROVED",
} as const;

export const NOTIFICATION_STATUSES = {
  PENDING: "PENDING",
} as const;
