export const WORKFLOW_STATUSES = {
  COMPLETED: "COMPLETED",
  FAILED: "FAILED",
} as const;

export const WORKFLOW_STEPS = {
  VALIDATE_RECOMMENDATION: "VALIDATE_RECOMMENDATION",
  ALLOCATE_WAREHOUSE: "ALLOCATE_WAREHOUSE",
  CREATE_PURCHASE_ORDER: "CREATE_PURCHASE_ORDER",
  COMPLETE_WORKFLOW: "COMPLETE_WORKFLOW",
} as const;

export const WORKFLOW_FAILURE_REASONS = {
  RECOMMENDATION_NOT_APPROVED: "RECOMMENDATION_NOT_APPROVED",
  RECOMMENDATION_NOT_REORDER: "RECOMMENDATION_NOT_REORDER",
  NO_REPLENISHMENT_REQUIRED: "NO_REPLENISHMENT_REQUIRED",
  ALLOCATION_OUT_OF_STOCK: "ALLOCATION_OUT_OF_STOCK",
  ALLOCATION_FAILED: "ALLOCATION_FAILED",
  PURCHASE_ORDER_FAILED: "PURCHASE_ORDER_FAILED",
} as const;
